

CREATE TABLE Project."User"
(
   UserID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY ,
   FirstName NVARCHAR(32) NOT NULL,
   LastName NVARCHAR(32) NOT NULL ,
   EmailAdress NVARCHAR(128) NOT NULL ,
   CreatedOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET()),
   UpdatedOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET()),
   "Password" NVARCHAR(128) NOT NULL,
   UNIQUE(FirstName, LastName, EmailAdress)
);

CREATE TABLE Project."Admin"
(
   AdminID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY ,
   UserID INT NOT NULL FOREIGN KEY,
   CreatedOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET()),
   UpdatedOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET())
);

CREATE TABLE Project.Customer
(
   CustomerID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY ,
   UserID INT NOT NULL FOREIGN KEY,
   CreatedOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET()),
   UpdatedOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET())
);

CREATE TABLE Project.Ticket
(
   CustomerID INT NOT NULL FOREIGN KEY ,
   ShowingID INT NOT NULL FOREIGN KEY ,
   IsActive BIT NOT NULL,
   CreatedOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET()),
   UpdatedOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET()),
   PRIMARY KEY(CustomerID, ShowingID)
);

CREATE TABLE Project.Theater
(
	TheaterID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	TheaterName NVARCHAR(32) NOT NULL,
	[Location] NVARCHAR(32) NOT NULL,
	IsActive BIT NOT NULL,
	CreatedOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET()),
	UpdatedOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET()),
	UNIQUE(TheaterName, [Location])
);

--Documentation says Release Year should be Unique, but that doesn't make sense?

CREATE TABLE Project.Movie
(
	MovieID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	MovieName NVARCHAR(32) NOT NULL,
	ReleaseYear INT NOT NULL,
	Genre NVARCHAR(32) NOT NULL,
	IsActive BIT NOT NULL,
	CreatedOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET()),
	UpdatedOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET()),
	UNIQUE(MovieName)
);

CREATE TABLE Project.Showing
(
	ShowingID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	TheaterName NVARCHAR(32) NOT NULL FOREIGN KEY REFERENCES Theater(TheaterName),
	MovieName NVARCHAR(32) NOT NULL FOREIGN KEY REFERENCES Movie(MovieName),
	Room INT NOT NULL,
	ShowTime TIME NOT NULL,
	IsActive BIT NOT NULL,
	CreatedOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET()),
	UpdatedOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET()),
	UNIQUE(Room, ShowTime)
);